/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    'company-settings': CompanySettings;
  };
  globalsSelect: {
    'company-settings': CompanySettingsSelect<false> | CompanySettingsSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Create pages simply: sections first, then page info, menu and publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Defines the recommendations shown below. It does not add sections automatically.
   */
  pageType?:
    | (
        | 'home'
        | 'landing'
        | 'service'
        | 'product'
        | 'institutional'
        | 'news'
        | 'education'
        | 'event'
        | 'contact'
        | 'free'
      )
    | null;
  /**
   * Add pure content slices. There is no visual configuration: the site decides the design automatically.
   */
  sections?: (HeroSlice | FeatureGridSlice | CTASlice | CanvasSlice)[] | null;
  /**
   * This name is also used as the URL base if you leave it empty.
   */
  title: string;
  /**
   * Example: services/web-design. For the home page use home.
   */
  slug: string;
  /**
   * Enable this if the page should appear in the main navigation.
   */
  showInNavigation?: boolean | null;
  /**
   * Leave empty for a main page. Choose a parent page if it should live inside another one.
   */
  parentPage?: (number | null) | Page;
  /**
   * If empty, the page name is used.
   */
  navigationLabel?: string | null;
  /**
   * Lower numbers appear first.
   */
  navigationOrder?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSlice".
 */
export interface HeroSlice {
  /**
   * Describes intent. The frontend decides the final layout.
   */
  purpose: 'clear-intro' | 'product-focus' | 'campaign' | 'institutional';
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  backgroundMedia?: (number | null) | Media;
  media?: (number | null) | Media;
  actions?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Reserved for the Hybrid Visual Builder: coordinates, scale, layers and responsive overrides sent from preview.
   */
  visualOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSlice';
}
/**
 * Library for website images, videos, SVGs and downloadable documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  mediaType: 'image' | 'video' | 'document' | 'other';
  /**
   * Helps find the right asset and avoid using logos or favicons as regular content.
   */
  usageType: 'general' | 'logo' | 'hero' | 'gallery' | 'video' | 'favicon' | 'ogImage' | 'download';
  folder?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  poster?: (number | null) | Media;
  description?: string | null;
  credits?: string | null;
  copyright?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridSlice".
 */
export interface FeatureGridSlice {
  /**
   * Choose editorial intent, not design.
   */
  purpose: 'simple-grid' | 'bento-showcase' | 'editorial';
  eyebrow?: string | null;
  title: string;
  intro?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        icon?: string | null;
        media?: (number | null) | Media;
        link?: {
          label?: string | null;
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Reserved for the Hybrid Visual Builder: coordinates, scale, layers and responsive overrides sent from preview.
   */
  visualOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGridSlice';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTASlice".
 */
export interface CTASlice {
  purpose: 'contact' | 'conversion' | 'subscription' | 'navigation';
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  actions?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  finePrint?: string | null;
  /**
   * Reserved for the Hybrid Visual Builder: coordinates, scale, layers and responsive overrides sent from preview.
   */
  visualOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaSlice';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CanvasSlice".
 */
export interface CanvasSlice {
  title: string;
  backgroundMedia?: (number | null) | Media;
  /**
   * Stores elements, positions, styles, layers and breakpoints for the visual editor.
   */
  canvas?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'canvasSlice';
}
/**
 * Reusable case studies for social proof sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  client?: string | null;
  summary?: string | null;
  challenge?: string | null;
  solution?: string | null;
  result?: string | null;
  media?: (number | null) | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reusable testimonials for trust and conversion sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  role?: string | null;
  media?: (number | null) | Media;
  featured?: boolean | null;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mini CRM to review, assign and follow up website messages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  firstName: string;
  lastName?: string | null;
  fullName?: string | null;
  phone: string;
  email: string;
  subject: string;
  message: string;
  status: 'new' | 'contacted' | 'followUp' | 'inProgress' | 'replied' | 'won' | 'lost' | 'archived';
  priority: 'low' | 'normal' | 'high' | 'urgent';
  assignedTo?: (number | null) | User;
  leadTags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  internalNotes?: string | null;
  followUpHistory?:
    | {
        date?: string | null;
        note: string;
        nextActionAt?: string | null;
        id?: string | null;
      }[]
    | null;
  lastResponseAt?: string | null;
  nextActionAt?: string | null;
  lostReason?: string | null;
  emailSent?: boolean | null;
  emailRecipients?:
    | {
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  emailError?: string | null;
  source?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal users and admin panel access roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Foundation for granular permissions. The app keeps broad permissions until the security phase is implemented.
   */
  role: 'superAdmin' | 'admin' | 'editor' | 'marketing' | 'viewer' | 'client';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageType?: T;
  sections?:
    | T
    | {
        heroSlice?: T | HeroSliceSelect<T>;
        featureGridSlice?: T | FeatureGridSliceSelect<T>;
        ctaSlice?: T | CTASliceSelect<T>;
        canvasSlice?: T | CanvasSliceSelect<T>;
      };
  title?: T;
  slug?: T;
  showInNavigation?: T;
  parentPage?: T;
  navigationLabel?: T;
  navigationOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSlice_select".
 */
export interface HeroSliceSelect<T extends boolean = true> {
  purpose?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  backgroundMedia?: T;
  media?: T;
  actions?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  visualOverrides?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridSlice_select".
 */
export interface FeatureGridSliceSelect<T extends boolean = true> {
  purpose?: T;
  eyebrow?: T;
  title?: T;
  intro?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        media?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        id?: T;
      };
  visualOverrides?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTASlice_select".
 */
export interface CTASliceSelect<T extends boolean = true> {
  purpose?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  actions?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  finePrint?: T;
  visualOverrides?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CanvasSlice_select".
 */
export interface CanvasSliceSelect<T extends boolean = true> {
  title?: T;
  backgroundMedia?: T;
  canvas?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  mediaType?: T;
  usageType?: T;
  folder?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  poster?: T;
  description?: T;
  credits?: T;
  copyright?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  summary?: T;
  challenge?: T;
  solution?: T;
  result?: T;
  media?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  media?: T;
  featured?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  phone?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  priority?: T;
  assignedTo?: T;
  leadTags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  internalNotes?: T;
  followUpHistory?:
    | T
    | {
        date?: T;
        note?: T;
        nextActionAt?: T;
        id?: T;
      };
  lastResponseAt?: T;
  nextActionAt?: T;
  lostReason?: T;
  emailSent?: T;
  emailRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  emailError?: T;
  source?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Single center for company, brand, contact, footer, social links, SEO and legal text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings".
 */
export interface CompanySettings {
  id: number;
  /**
   * Defines the global visual tone. The frontend uses it to interpret slices without asking for visual settings per section.
   */
  siteProfile: 'government' | 'saas-apple' | 'agency' | 'ecommerce' | 'education';
  /**
   * If a visitor has not chosen a language, the public site loads this language.
   */
  defaultLanguage: 'es' | 'en';
  commercialName: string;
  legalName?: string | null;
  slogan?: string | null;
  shortDescription?: string | null;
  longDescription?: string | null;
  mainEmail?: string | null;
  mainPhone?: string | null;
  whatsapp?: string | null;
  address?: string | null;
  countryCity?: string | null;
  businessHours?: string | null;
  logoPrimary?: (number | null) | Media;
  logoSecondary?: (number | null) | Media;
  favicon?: (number | null) | Media;
  ogImage?: (number | null) | Media;
  /**
   * HEX format. Example: #0F172A.
   */
  colorPrimary: string;
  /**
   * HEX format. Example: #0F172A.
   */
  colorSecondary: string;
  /**
   * HEX format. Example: #0F172A.
   */
  colorAccent: string;
  /**
   * HEX format. Example: #0F172A.
   */
  colorBackground: string;
  /**
   * HEX format. Example: #0F172A.
   */
  colorTextPrimary: string;
  /**
   * HEX format. Example: #0F172A.
   */
  colorTextSecondary: string;
  facebookUrl?: string | null;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  linkedinUrl?: string | null;
  youtubeUrl?: string | null;
  twitterUrl?: string | null;
  whatsappUrl?: string | null;
  contactEyebrow?: string | null;
  contactHeadline?: string | null;
  contactIntro?: string | null;
  /**
   * You can add multiple emails. Each form message is saved in the admin and sent to these addresses.
   */
  contactRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The footer is assembled from company details, social links and manual links.
   */
  footerIsEnabled?: boolean | null;
  footerShowLogo?: boolean | null;
  /**
   * Optional. If empty, the secondary or primary brand logo is used.
   */
  footerLogo?: (number | null) | Media;
  footerShowCompanyName?: boolean | null;
  footerCompanyNameOverride?: string | null;
  footerShortDescription?: string | null;
  footerAdditionalText?: string | null;
  footerColumns?:
    | {
        title: string;
        contentType: 'manualLinks' | 'socialLinks' | 'contact' | 'customText';
        customText?: string | null;
        links?:
          | {
              label: string;
              url: string;
              openInNewTab?: boolean | null;
              isActive?: boolean | null;
              order?: number | null;
              id?: string | null;
            }[]
          | null;
        order?: number | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. If you do not add links here, the site uses the main social links from General Settings.
   */
  footerSocialLinks?:
    | {
        name: string;
        type:
          | 'facebook'
          | 'instagram'
          | 'tiktok'
          | 'linkedin'
          | 'youtube'
          | 'twitter'
          | 'whatsapp'
          | 'website'
          | 'other';
        url: string;
        iconName?: string | null;
        showInFooter?: boolean | null;
        showInHeader?: boolean | null;
        openInNewTab?: boolean | null;
        isActive?: boolean | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  footerUseCompanySettings?: boolean | null;
  footerEmail?: string | null;
  footerPhone?: string | null;
  footerWhatsapp?: string | null;
  footerAddress?: string | null;
  footerBusinessHours?: string | null;
  footerCountry?: string | null;
  footerCity?: string | null;
  footerCopyrightText?: string | null;
  footerPrivacyPageId?: number | null;
  footerTermsPageId?: number | null;
  footerLegalTextOverride?: string | null;
  defaultMetaTitle: string;
  defaultMetaDescription: string;
  /**
   * Separate keywords with commas.
   */
  globalKeywords?: string | null;
  canonicalBaseUrl?: string | null;
  copyrightText?: string | null;
  privacyPolicy?: string | null;
  termsAndConditions?: string | null;
  footerLegalText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings_select".
 */
export interface CompanySettingsSelect<T extends boolean = true> {
  siteProfile?: T;
  defaultLanguage?: T;
  commercialName?: T;
  legalName?: T;
  slogan?: T;
  shortDescription?: T;
  longDescription?: T;
  mainEmail?: T;
  mainPhone?: T;
  whatsapp?: T;
  address?: T;
  countryCity?: T;
  businessHours?: T;
  logoPrimary?: T;
  logoSecondary?: T;
  favicon?: T;
  ogImage?: T;
  colorPrimary?: T;
  colorSecondary?: T;
  colorAccent?: T;
  colorBackground?: T;
  colorTextPrimary?: T;
  colorTextSecondary?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  linkedinUrl?: T;
  youtubeUrl?: T;
  twitterUrl?: T;
  whatsappUrl?: T;
  contactEyebrow?: T;
  contactHeadline?: T;
  contactIntro?: T;
  contactRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  footerIsEnabled?: T;
  footerShowLogo?: T;
  footerLogo?: T;
  footerShowCompanyName?: T;
  footerCompanyNameOverride?: T;
  footerShortDescription?: T;
  footerAdditionalText?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        contentType?: T;
        customText?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              isActive?: T;
              order?: T;
              id?: T;
            };
        order?: T;
        isActive?: T;
        id?: T;
      };
  footerSocialLinks?:
    | T
    | {
        name?: T;
        type?: T;
        url?: T;
        iconName?: T;
        showInFooter?: T;
        showInHeader?: T;
        openInNewTab?: T;
        isActive?: T;
        order?: T;
        id?: T;
      };
  footerUseCompanySettings?: T;
  footerEmail?: T;
  footerPhone?: T;
  footerWhatsapp?: T;
  footerAddress?: T;
  footerBusinessHours?: T;
  footerCountry?: T;
  footerCity?: T;
  footerCopyrightText?: T;
  footerPrivacyPageId?: T;
  footerTermsPageId?: T;
  footerLegalTextOverride?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  globalKeywords?: T;
  canonicalBaseUrl?: T;
  copyrightText?: T;
  privacyPolicy?: T;
  termsAndConditions?: T;
  footerLegalText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}